language: python
python:
  - 3.6
git:
  submodules: false
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
notifications:
  email: false
script:
  - python3 formicID/get_dataset.py -c formicID/configs/config.json
