---
title: "HDP experiments"
author: "MarijnJABoer"
date: "14/05/2018"
output:
  md_document:
    variant: markdown_github
    toc: true
    fig_width: 7
    fig_height: 6
---

```{r Setup, echo=T, message=FALSE, warning=FALSE, results='hide'}
setwd("~/Internships/Internship CNN 2017-2018/FormicID/stat/hdp")
data_dir <- file.path("shottype training")
plot_out_name <- "Uncleaned dataset.pdf"
library(ggplot2) # for plotting
library(gridExtra)
library(gtable)
library(grid)
library(reshape2)
library(magick)
library(ggpubr)
library(cowplot)

```

## Reading data

```{r Reading data}
needed <- c("epoch", "val_acc", "val_top_k_cat_accuracy")
dorsal <-
    read.csv(
        file.path(data_dir, "dorsal", "20180518_094541_metricslog.csv"),
        header = TRUE,
        sep = ","
    )
dorsal <- dorsal[needed]
dorsal <- melt(dorsal, id = "epoch")
head <-
    read.csv(
        file.path(data_dir, "head", "20180523_084437_metricslog.csv"),
        header = TRUE,
        sep = ","
    )
head <- head[needed]
head <- melt(head, id = "epoch")
profile <-
    read.csv(
        file.path(data_dir, "profile", "20180516_094945_metricslog.csv"),
        header = TRUE,
        sep = ","
    )
profile <- profile[needed]
profile <- melt(profile, id = "epoch")
factor_rename <- factor(c("Validation accuracy","Validation top 3 accuracy"))
levels(dorsal$variable) <- factor_rename
levels(head$variable) <- factor_rename
levels(dorsal$variable) <- factor_rename

```

## Reading CMs

```{r Reading CMs}
dorsalcm <- image_read(file.path(data_dir, "dorsal", "cmdorsal.png"))
headcm <- image_read(file.path(data_dir, "head", "cmhead.png"))
profilecm <- image_read(file.path(data_dir, "profile", "cmprofile.png"))
```


```{r}
maxd <- max(dorsal$epoch, na.rm = TRUE)
maxh <- max(head$epoch, na.rm = TRUE)
maxp <- max(profile$epoch, na.rm = TRUE)
maxlist <- c(maxd, maxh, maxp)
max_x <- max(maxlist)
roundUp <- function(x, to = 10) {
    to * (x %/% to + as.logical(x %% to))
}
max_x <- roundUp(max_x, to = 25)
```


## Plotting

```{r Creating plots}
dd <-
    ggplot(data = dorsal, aes(x = epoch, y = value, colour = variable)) +
    geom_line() +
    scale_x_continuous(breaks = c(0, 25, 50, 75, 100, 125),
                       limits = c(0, max_x)) +
    scale_y_continuous(limits = c(0, 1), labels = scales::percent) +
    theme() +
    ylab(NULL) +
    # xlab(NULL) +
    # ggtitle("Dorsal") +
    theme(
        legend.position = "none",
        axis.text = element_text(size = 8), axis.title=element_text(size=10,face="bold")
    ) +
    background_grid(major = c("xy"), minor = ("xy"))
ddlegend <- dd +
    theme(legend.position = "right",
          legend.title = element_blank())


hh <-
    ggplot(data = head, aes(x = epoch, y = value, colour = variable)) +
    geom_line() +
    scale_x_continuous(breaks = c(0, 25, 50, 75, 100, 125),
                       limits = c(0, max_x)) +
    scale_y_continuous(limits = c(0, 1), labels = scales::percent) +
    ylab(NULL) +
    # xlab(NULL) +
    # ggtitle("Head") +
    theme(
        legend.position = "none",
        axis.text = element_text(size = 8), axis.title=element_text(size=10,face="bold")
    ) +
    background_grid(major = c("xy"), minor = ("xy"))
pp <-
    ggplot(data = profile, aes(x = epoch, y = value, colour = variable)) +
    geom_line() +
    scale_x_continuous(breaks = c(0, 25, 50, 75, 100, 125),
                       limits = c(0, max_x)) +
    scale_y_continuous(limits = c(0, 1), labels = scales::percent) +
    ylab(NULL) +
    # xlab(NULL) +
    # ggtitle("Profile") +
    theme(
        legend.position = "none",
        axis.text = element_text(size = 8), axis.title=element_text(size=10,face="bold")
    ) +
    background_grid(major = c("xy"), minor = ("xy"))

```

```{r}
evolution <- plot_grid(
    dd + xlab(NULL) + ggtitle("Dorsal"),
    hh + xlab(NULL) + ggtitle("Head"),
    pp + xlab(NULL) + ggtitle("Profile"),
    nrow = 1,
    ncol = 3,
    scale = 0.9
) + #perhaps reduce this for a bit more space
    draw_label(
        "Epoch",
        x = 0.5,
        y = 0,
        vjust = -0.5,
        angle = 0
    ) +
    draw_label(
        "Accuracy",
        x = 0,
        y = 0.5,
        vjust = 1.5,
        angle = 90
    )
legend <- get_legend(ddlegend)
legend_bottom <- plot_grid(legend, ncol = 2)
evolution_final <- plot_grid(legend_bottom, evolution, nrow=2, ncol=1,  rel_heights = c(0.1, 1))
evolution_final
```


## Creating a combined plot and saving to PDF

```{r Plotting and saving to pdf}
ggdorsal <- ggdraw() + draw_image(dorsalcm, scale = 1)
gghead <- ggdraw() + draw_image(headcm, scale = 1)
ggprofile <- ggdraw() + draw_image(profilecm, scale = 1)
legend <- get_legend(ddlegend)
legend_bottom <- plot_grid(legend, ncol = 2)

# Dorsal
titledd <- ggdraw() +
    draw_label("Dorsal shottype", fontface = 'bold')
graphsdd <- plot_grid(
    dd,
    ggdorsal,
    ncol = 2,
    nrow = 1,
    align = "v",
    rel_widths = c(1,0.85), 
    labels = c("A", "B"), label_x = .16
)
plotdd <-
    plot_grid(titledd,
              graphsdd,
              ncol = 1,
              rel_heights = c(0.1, 1))
# Head
titlehh <- ggdraw() +
    draw_label("Head shottype", fontface = 'bold')
graphshh <- plot_grid(
    hh,
    gghead,
    ncol = 2,
    nrow = 1,
    align = "v",
    rel_widths = c(1,0.85), 
    labels = c("C", "D"), label_x = .16
)
plothh <-
    plot_grid(titlehh,
              graphshh,
              ncol = 1,
              rel_heights = c(0.1, 1))
# Profile
titlepp <- ggdraw() +
    draw_label("Profile shottype", fontface = 'bold')
graphspp <- plot_grid(
    pp,
    ggprofile,
    ncol = 2,
    nrow = 1,
    align = "v",
    rel_widths = c(1,0.85), 
    labels = c("E", "F"), label_x = .16
)
plotpp <-
    plot_grid(titlepp,
              graphspp,
              ncol = 1,
              rel_heights = c(0.1, 1))

graphs <- plot_grid(plotdd,
                    plothh,
                    plotpp,
                    ncol = 1,
                    nrow = 3)

final <- plot_grid(
    graphs,
    legend_bottom,
    ncol = 1,
    nrow = 2,
    rel_heights = c(1, .05)
)

save_plot(plot_out_name,
          final,
          base_width = 8.27,
          base_height =  11.69)

```

